- name: Log in to Docker Hub
  community.docker.docker_login:
    username: "{{ dockerhub_user }}"
    password: "{{ dockerhub_password }}"

- name: Push image to Docker Hub
  community.docker.docker_image:
    name: "{{ dockerhub_user }}/fastapi-demo"
    tag: latest
    push: true
